<a href="https://colab.research.google.com/github/omarfarukcse/Machine-learning/blob/Pandas/Pandas_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

print(f"Pandas Version check : {pd.__version__}")

Pandas Version check : 2.2.2

In [8]:
#Creating A Series
cars = pd.Series(["BMW","Toyota","Honda","BYD","Mercedece"])
print(cars)

0          BMW
1       Toyota
2        Honda
3          BYD
4    Mercedece
dtype: object

In [10]:
colors = pd.Series(["Black","White","Red","Blue","Merun"])
colors

0    Black
1    White
2      Red
3     Blue
4    Merun
dtype: object

In [11]:
car_data = pd.DataFrame({"Car_type":cars,
                         "Color":colors})
car_data

    Car_type  Color
0        BMW  Black
1     Toyota  White
2      Honda    Red
3        BYD   Blue
4  Mercedece  Merun